### PR TITLE
[PLT-587] Pin dependencies

### PR DESCRIPTION
**Pull request by Yass-Seer**
## :pencil: Description
Dependencies were unpinned causing a couple of issues:

1. `seer-py` is a dependency for `seer-worker`, which uses pinned dependencies. When building `seer-worker` we were getting a `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` error. This is because `numpy` recently move to version `2.X.X` which has incompatible changes with prior versions
2. `urllib3 2.X.X` has changes that are not yet support by `requests`, which is required for `gql`. Again, due to the unpinned nature of the dependencies `seer-py` wasn't working (it's kind of a miracle it's been working at all....)

## :hatching_chick: Changes

- Pin `numpy`, `pandas`, `urllib3` & `graphql-core` to match `seer-worker`
- Pin all other dependencies to the latest at the time of this PR
- Update the package & CI to use python 3.8

## :white_check_mark: Testing
Created a new virtual environment, installed the dependencies & ran the tests. To reproduce:

```
python -m venv seerpyenv
source seerpyenv/bin/activate
pip install -r requirements.txt -r requirements_test.txt
pytest
```

Hopefully you get something that looks like this:
image

### CODE REVIEW

**Review by robrkerr — APPROVED** [review]
Nice one!

**Comment by robrkerr** [comment]
@Yass-Seer hmm actually it [seems like](https://buildkite.com/seer-medical/seer-py/builds/776#0190581d-d6da-4732-815c-5aec08435334) CI's not happy with that version of numpy for some reason...

**Comment by Yass-Seer** [comment]
> @Yass-Seer hmm actually it [seems like](https://buildkite.com/seer-medical/seer-py/builds/776#0190581d-d6da-4732-815c-5aec08435334) CI's not happy with that version of numpy for some reason...

Turns out the package & our CI were using python 3.6, which that version of numpy doesn't support. Given python 3.6 has reached end of life I've updated to 3.8+, which is a bit old but still quite popular.

**Comment by norrishd** [comment]
Just checking, is the intention to make a `seer-py` release and pin that in `seer-worker`? Because it look like `seer-worker` just clones `seer-py` then does `pip install`, i.e. will use the still-unversioned `install_requires` packages in _setup.py_:
https://github.com/seermedical/seer-worker/blob/3a44cbd9ba65b4d328cf57fbf77b71fb8ea78d89/Dockerfile#L49

**Review by norrishd — COMMENTED** [review]
Looks like an improvement, but see my question about whether this will actually fix the current `seer-worker` problem

**Comment by Yass-Seer** [comment]
> I might be wrong but... will this fix things? It look like `seer-worker` just clones `seer-py` then does `pip install`: https://github.com/seermedical/seer-worker/blob/3a44cbd9ba65b4d328cf57fbf77b71fb8ea78d89/Dockerfile#L47-L49
> 
> I.e. won't it still use the unversioned `install_requires` packages in _setup.py_, and therefore install the incompatible more recent versions of `numpy` and `urllib`?
> 
> If so, might need to do something like `numpy<=2.0.0` in the _setup.py_

Yeah good catch. I also forgot to bump the version for this repo

**Comment by robrkerr** [comment]
> I might be wrong but... will this fix things? It look like `seer-worker` just clones `seer-py` then does `pip install`: https://github.com/seermedical/seer-worker/blob/3a44cbd9ba65b4d328cf57fbf77b71fb8ea78d89/Dockerfile#L47-L49
> I.e. won't it still use the unversioned `install_requires` packages in _setup.py_, and therefore install the incompatible more recent versions of `numpy` and `urllib`?
> If so, might need to do something like `numpy<=2.0.0` in the _setup.py_

@norrishd @Yass-Seer I might be wrong but I think with the testing that @ckornacker and I were doing (trying to get CI for the worker to work using this branch) this change had worked with only the changes to `requirements.txt`. Is that right @ckornacker?

**Review by robrkerr — APPROVED** [review]
Changes look good and I've tested ([here](https://buildkite.com/seer-medical/seer-worker/builds/2568)) that this change combined with the seer-hub-sense-sdk change ([here](https://github.com/seermedical/seer-hub-sense-sdk/pull/44)) sucessfully resolve the build issues with the worker in CI.

**Comment by ckornacker** [comment]
> I might be wrong but I think with the testing that @ckornacker and I were doing (trying to get CI for the worker to work using this branch) this change had worked with only the changes to `requirements.txt`. Is that right @ckornacker?

correct :+1: I think it might only install dependencies through setup.py if in editable mode (-e parameter)?

**Comment by norrishd** [comment]
> > I might be wrong but I think with the testing that @ckornacker and I were doing (trying to get CI for the worker to work using this branch) this change had worked with only the changes to `requirements.txt`. Is that right @ckornacker?
> 
> correct 👍 I think it might only install dependencies through setup.py if in editable mode (-e parameter)?

@ckornacker @robrkerr I'm almost certain `pip install` only uses the _setup.py_ not the _requirements.txt_ (regardless of whether `-e` is passed), and ChatGPT at least [agrees](https://chatgpt.com/share/d3379d3b-a68e-4885-a500-df5d2946bd60).

The `seer-hub-sense-sdk` stipulates `numpy<2.0.0`, so what would've happened is the dependency resolver incorporated that restraint, and since `seer-py` had no version restrictions in its _setup.py_ it used <2.0.0. If you removed `seer-hub-sense-sdk` as a dependency and tried again I'd expect it to default to the latest numpy that is compatible with all other pinned version requirements.

**Review by norrishd — APPROVED** [review]
LGTM 🚀

**Pull request merged**
