### PR TITLE
Add patient ID to mood survey query

### PR DESCRIPTION
**Pull request by dkeden**
Small PR to add patient ID to the mood survey query

### CODE REVIEW

**Review by seerwill — DISMISSED** [review]
Looks fine to me, might be worth coordinate with @bjdoyle around #110  before merging.

**Comment by bjdoyle** [comment]
@dkeden I've merged my changes from the last PR into this. You might want to check you're happy. It would also be good if you could update the test files with this change (for completeness - though the tests pass as is).

**Review by seerwill — DISMISSED** [review]

**Comment by dkeden** [comment]
Awesome, thanks @bjdoyle. I've just updated the mood survey test files. I don't think there's anything else I need to do?

**Review by seerwill — APPROVED** [review]

**Review by bjdoyle — CHANGES_REQUESTED** [review]
Need to change the result csvs to reflect the json (I think you already saw this)

**Review by bjdoyle — CHANGES_REQUESTED** [review]
Sorry, I see you already did, but there is still a test error

**Review by seerwill — DISMISSED** [review]
👍

**Pull request closed without merging**
